### ISSUE TITLE
Should the simple mode (and all) have a license by default

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/ro-crate-modes#28]
As required in the https://www.researchobject.org/ro-crate/specification/1.1/root-data-entity.html#direct-properties-of-the-root-data-entity

**Comment by moisbo** [comment]
Hi Rosanna -- since you were working on this I have assigned this to you. Can you please check that we can add a license to all modes, starting with the simple mode? I updated the modes repo and still cannot add a license or link to a license with crate-o. not sure why?

**Comment by rosanna-smith** [comment]
Checked this further with Alvin now: license-test branch added to ro-crate-modes that has the creative work update to the simple mode. According to https://schema.org/license this should have the types CreativeWork and URL so I've added both, but this also adds the following subclasses due to this section of the simple mode:
```    "classes": {
      "CreativeWork": {
        "hasSubclass": [
          "Dataset",
          "File",
          "SoftwareApplication"
        ],
```

<img width="596" alt="Screenshot 2024-09-03 at 3 30 42 pm" src="https://github.com/user-attachments/assets/06b26772-4d7c-46e6-a20e-1806ed3c0cec">
If that part of the simple mode isn't needed I can remove that part as well.

**Comment by rosanna-smith** [comment]
Made some further updates to the license-test branch - schema.json also has a license now.

**Comment by moisbo** [comment]
tested and working thank you Rosanna
